---

name: "Docs"

env:
  needs_nix_setup: false

# yamllint disable-line rule:truthy
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  rust:
    name: Rust docs
    runs-on: self-hosted-hopname: "Build docs"

env:
  needs_nix_setup: false

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  rust:
    name: Rust docs
    # big runner is needed because building docs involves building Rust code
    runs-on: self-hosted-hoprnet-bigger
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        if: env.needs_nix_setup == true
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v15
        if: env.needs_nix_setup == true
        with:
          name: hoprnet
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        env:
          USER: runner

      - name: Build docs
        run: nix build .#docs -L

      - name: Increase git buffer size
        if: github.ref == 'refs/heads/master'
        run: git config --global http.postBuffer 524288000

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actiname: "Build docs"

env:
  needs_nix_setup: false

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  rust:
    name: Architecture | System design
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build System Design draft
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: docs
